$(document).ready(function(){
  $(".top-scroll").click(function(event) {
    event.preventDefault();
    $("html, body").animate({ scrollTop: 0 }, "slow");
  });
  $(".small").click(function(event){
    event.preventDefault();
    $(".menu").toggle();
  });
  $(".logo").click(function(event){
    event.preventDefault();
    $(".service-container").hide();
    $(".about-container").hide();
    $(".contact-container").hide();
    $(".nav-container").fadeIn(1000).delay(3000);
  });
  $(".services").click(function(event){
    event.preventDefault();
    $(".nav-container").hide();
    $(".about-container").hide();
    $(".contact-container").hide();
    $(".service-container").fadeIn(1000).delay(3000);
  });
  $(".about").click(function(event){
    event.preventDefault();
    $(".nav-container").hide();
    $(".about-container").hide();
    $(".service-container").hide();
    $(".about-container").fadeIn(1000).delay(3000);
  });
  $(".contact").click(function(event){
    event.preventDefault();
    $(".nav-container").hide();
    $(".about-container").hide();
    $(".service-container").hide();
    $(".contact-container").fadeIn(1000).delay(3000);
  });
});
